CREATE DATABASE MatchFinderDB;
USE MatchFinderDB;

CREATE TABLE equipos (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      varchar(100) NOT NULL,
    descripcion varchar(500) NOT NULL,
    tipo        varchar(20)  NOT NULL,
    CONSTRAINT uq_equipos_nombre UNIQUE (nombre),
    CONSTRAINT ck_equipos_tipo CHECK (tipo IN ('FUTBOL_5', 'FUTBOL_11'))
);

CREATE TABLE usuarios (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    varchar(50)  NOT NULL,
    email     varchar(100) NOT NULL,
    password  varchar(255) NOT NULL,
    rol       varchar(20)  NOT NULL,
    equipo_id integer,
    CONSTRAINT uq_usuarios_nombre UNIQUE (nombre),
    CONSTRAINT uq_usuarios_email  UNIQUE (email),
    CONSTRAINT ck_usuarios_rol    CHECK (rol IN ('USUARIO', 'OWNER')),
    CONSTRAINT fk_usuarios_equipo FOREIGN KEY (equipo_id) REFERENCES equipos (id)
);

CREATE INDEX idx_usuarios_equipo ON usuarios (equipo_id);

CREATE TABLE solicitudes_amistad (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remitente_id    integer     NOT NULL,
    destinatario_id integer     NOT NULL,
    estado          varchar(20) NOT NULL,
    CONSTRAINT fk_solicitudes_remitente    FOREIGN KEY (remitente_id)    REFERENCES usuarios (id),
    CONSTRAINT fk_solicitudes_destinatario FOREIGN KEY (destinatario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_solicitudes_estado CHECK (estado IN ('PENDIENTE', 'ACEPTADA', 'RECHAZADA'))
);

CREATE INDEX idx_solicitudes_destinatario ON solicitudes_amistad (destinatario_id);
CREATE INDEX idx_solicitudes_remitente    ON solicitudes_amistad (remitente_id);

CREATE TABLE amistades (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id integer NOT NULL,
    amigo_id   integer NOT NULL,
    CONSTRAINT uq_amistades_par UNIQUE (usuario_id, amigo_id),
    CONSTRAINT fk_amistades_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_amistades_amigo   FOREIGN KEY (amigo_id)   REFERENCES usuarios (id)
);

CREATE TABLE torneos (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           varchar(100) NOT NULL,
    tipo             varchar(20)  NOT NULL,
    cantidad_equipos integer      NOT NULL,
    estado           varchar(20)  NOT NULL,
    CONSTRAINT ck_torneos_tipo   CHECK (tipo IN ('FUTBOL_5', 'FUTBOL_11')),
    CONSTRAINT ck_torneos_estado CHECK (estado IN ('ACTIVO', 'FINALIZADO'))
);

CREATE TABLE torneo_equipos (
    torneo_id integer NOT NULL,
    equipo_id integer NOT NULL,
    PRIMARY KEY (torneo_id, equipo_id),
    CONSTRAINT fk_torneo_equipos_torneo FOREIGN KEY (torneo_id) REFERENCES torneos (id),
    CONSTRAINT fk_torneo_equipos_equipo FOREIGN KEY (equipo_id) REFERENCES equipos (id)
);

CREATE TABLE partidos (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    torneo_id     integer NOT NULL,
    equipo_uno_id integer NOT NULL,
    equipo_dos_id integer NOT NULL,
    ganador_id    integer NOT NULL,
    CONSTRAINT fk_partidos_torneo FOREIGN KEY (torneo_id)     REFERENCES torneos (id),
    CONSTRAINT fk_partidos_uno    FOREIGN KEY (equipo_uno_id) REFERENCES equipos (id),
    CONSTRAINT fk_partidos_dos    FOREIGN KEY (equipo_dos_id) REFERENCES equipos (id),
    CONSTRAINT fk_partidos_ganador FOREIGN KEY (ganador_id)   REFERENCES equipos (id)
);

CREATE INDEX idx_partidos_torneo ON partidos (torneo_id);

CREATE UNIQUE INDEX uq_un_solo_owner   ON usuarios ((1)) WHERE rol = 'OWNER';
CREATE UNIQUE INDEX uq_un_torneo_activo ON torneos ((1)) WHERE estado = 'ACTIVO';
